### ISSUE TITLE
> Merge branch 'feature/addgems' of github.com:AndreU73/TaskManager into feature/addgems

### ISSUE THREAD

**Issue by AndreU73** [AndreU73/TaskManager#8]
я его удаляю последний коммит, делаю ребэйз, и пуш (вот что он выдает) (я Вам в тг написал личный вопрос)

git push --all                                                                                                                             1 ↵ andre@MacBook-Air-Andrej
To github.com:AndreU73/TaskManager.git
 ! [rejected]        develop -> develop (non-fast-forward)
error: failed to push some refs to 'github.com:AndreU73/TaskManager.git'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. Check out this branch and integrate the remote changes
hint: (e.g. 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by greybutton** [comment]
после ребэйза нужно пушить с форсом `git push --force`

**Comment by AndreU73** [comment]
git push --force                                                                                                                           1 ↵ andre@MacBook-Air-Andrej
fatal: You are not currently on a branch.
To push the history leading to the current (detached HEAD)
state now, use

    git push origin HEAD:<name-of-remote-branch>

**Comment by AndreU73** [comment]
Мне уже кажется проще все откатить до первоначального состояния и сделать по новой
